### ISSUE TITLE
Release plan for support on tokio v0.3?

### ISSUE THREAD

**Issue by fanatid** [akshayknarayan/hyper-unix-connector#2]
https://tokio.rs/blog/2020-10-tokio-0-3

**Comment by akshayknarayan** [comment]
I currently have no plans to implement this, but I'm happy to review and merge a PR.

**Comment by akshayknarayan** [comment]
#3 merged tokio 1.0 support, released in v0.2.0 of this library.

**Comment by fanatid** [comment]
Great! Thanks! :tada:
